SOUND_BACKGROUND: "client/sound_sys/sounds/background_song.mp3"

SOUND_CAR_START: "client/sound_sys/sounds/car_start.wav"
SOUND_CAR_RUN: "client/sound_sys/sounds/car_running.wav"
SOUND_CAR_HORN: "client/sound_sys/sounds/car_horn.wav"
SOUND_CAR_STOP: "client/sound_sys/sounds/squealing.mp3"
SOUND_CAR_GEAR: "client/sound_sys/sounds/car_geardown.wav"
VIDEO_RECORDING_ON_OFF: "client/sound_sys/sounds/car_horn.wav"
SOUND_CAR_EXPLODES: "client/sound_sys/sounds/car_exploting.wav"