# Add height adn width of this
grass_tile: "map/grass.png"
straight_road_tile: "map/road_straight.png"
left_road_tile: "map/road_lower_turn.png"
right_road_tile: "map/road_upper_turn.png"
straight_road_mud_tile: "map/road_straight.png"
left_road_mud_tile: "map/road_lower_turn.png"
right_road_mud_tile: "map/road_upper_turn.png"

