grass_tile: "map/grass.png"
grass_tile_w: 512
grass_tile_h: 512

straight_road_tile: "map/straight_horizontal.png"
straight_road_tile_w: 512
straight_road_tile_h: 512

down_left_road_tile: "map/down_left.png"
down_left_road_tile_w: 512
down_left_road_tile_h: 512

down_right_road_tile: "map/down_right.png"
down_right_road_tile_w: 512
down_right_road_tile_h: 512

straight_vertical_tile: "map/straight_vertical.png"
straight_vertical_tile_w: 512
straight_vertical_tile_h: 512

straight_vertical_aux_tile: "map/straight_vertical_aux.png"
straight_vertical_aux_tile_w: 512
straight_vertical_aux_tile_h: 512

straight_horizontal_aux_tile: "map/straight_horizontal_aux.png"
straight_horizontal_aux_tile_w: 512
straight_horizontal_aux_tile_h: 512

up_left_road_tile: "map/up_left_curve.png"
up_left_road_tile_w: 512
up_left_road_tile_h: 512

up_right_road_tile: "map/up_right.png"
up_right_road_tile_w: 512
up_right_road_tile_h: 512

tree_spikes_tile: "decoration/tree_spikes.png"
tree_spikes_tile_w: 512
tree_spikes_tile_h: 512

tree_round_tile: "decoration/tree_round.png"
tree_round_tile_w: 512
tree_round_tile_h: 512

pavilion_blue_tile: "decoration/pavilion_blue.png"
pavilion_blue_tile_w: 512
pavilion_blue_tile_h: 512

finish_line: "decoration/Finish.png"
finish_line_w: 512
finish_line_h: 512